// Generated by CoffeeScript 1.6.1
(function() {
  var content, fs, summarize;

  fs = require('fs');

  summarize = require('./index');

  content = fs.readFileSync('test.txt').toString();

  console.log((summarize(content)).join('\n'));

}).call(this);
