// Generated by CoffeeScript 1.6.1
(function() {
  var content, fs, ratio, sparknotes, summarize;

  fs = require('fs');

  summarize = require('./index');

  content = fs.readFileSync('test.txt').toString();

  sparknotes = (summarize(content)).join('\n');

  ratio = ((1 - (sparknotes.length / content.length)) * 100).toFixed(2);

  console.log(sparknotes);

  console.log("\nText reduced " + ratio + "%, from " + content.length + " to " + sparknotes.length + " characters");

}).call(this);
